# Generated by Django 4.1.7 on 2023-03-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=200)),
                ('full_name', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read_by_admin', models.BooleanField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('response', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
