# Generated by Django 4.1.7 on 2023-03-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactus_is_read_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
