# Generated by Django 4.2 on 2023-05-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productgallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='img1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='img3',
        ),
    ]
