# Generated by Django 4.2 on 2023-04-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodels',
            name='url_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
