# Generated by Django 4.2 on 2023-04-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articlemodels_url_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleModels',
            new_name='ArticleCategoryModels',
        ),
    ]
