# Generated by Django 4.2 on 2023-04-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_articlemodels_articlecategorymodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategorymodels',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.articlecategorymodels'),
        ),
    ]
