# Generated by Django 4.2 on 2023-04-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlecategorymodels_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200)),
                ('image', models.ImageField(upload_to='images/article')),
                ('short_description', models.TextField()),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('selected_categories', models.ManyToManyField(to='article.articlecategorymodels')),
            ],
        ),
    ]
