# Generated by Django 4.2 on 2023-04-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_span',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.comments'),
        ),
    ]
