# Generated by Django 4.2 on 2023-04-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_comments_is_span_alter_comments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.TextField(),
        ),
    ]
