# Generated by Django 4.2 on 2023-04-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('site_url', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('copy_right', models.CharField(max_length=200)),
                ('about_us_text', models.CharField(max_length=200)),
                ('site_logo', models.ImageField(upload_to='images/site-setting')),
                ('is_main_setting', models.BooleanField()),
            ],
        ),
    ]
