# Generated by Django 4.2 on 2023-04-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0003_slidersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidersetting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
