# Generated by Django 4.2 on 2023-04-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0004_slidersetting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidersetting',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
